### ISSUE TITLE
Is the usages of stripe any different now, would you still recommend this approach?

### ISSUE THREAD

**Issue by 7sharp9** [cmatskas/StripeSample#2]

**Comment by MrCsabaToth** [comment]
I don't see any other approach where you wouldn't have to be PCI/PCI-DSS compliant. I'll store only the token in my DB so no sensitive data will be handled on my side. That's really favorable IMHO. Furthermore Stripe's REST API (I'm mainly think about the client side) gives desired freedom how you build your charge page.

I'm curious about other's opinion.

**Comment by cmatskas** [comment]
@mrCsabatoth sorry for he inordinate delay in my response. You are absolutely right. CC information should not touch your server. If that's he case, then you need to get certified and your process needs to adhere to PCI compliance rules. Hence the reason why the REST API is he easiest way to be compliant. I hope this helps
